# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vk

 pod 'Alamofire', '~> 4.8'
   pod 'RealmSwift'
   pod 'PromiseKit' 


   # pod 'Texture', '~>3.0'
   pod 'Texture'
 
   #pod 'AsyncDisplayKit'

   
   # add pods for desired Firebase products
   # https://firebase.google.com/docs/ios/setup#available-pods
   pod 'Firebase/Database'
   pod 'Firebase/Auth'

  target 'vkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vkUITests' do
    # Pods for testing
  end

end
